export const Message = {
  SUCCESS: 'SUCCESS',

  TOKEN_EXPIRED: 'TOKEN_EXPIRED',

  SOMETHING_WRONG: 'SOMETHING_WRONG',
  ACCOUNT_NOT_EXISTS: 'ACCOUNT_NOT_EXISTS',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  DELETE_ACCOUNT_SUCCESS: 'DELETE_ACCOUNT_SUCCESS',
  DELETE_SUCCESS: 'DELETE_SUCCESS',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  EMAIL_NOT_EXISTS: 'EMAIL_NOT_EXISTS',
  VALIDATE_ERROR: 'VALIDATE_ERROR',
  LOGIN_BY_PASSWORD: 'LOGIN_BY_PASSWORD',
  NOT_FOUND: 'NOT_FOUND',
  ITEM_EXISTS: 'ITEM_EXISTS',
  ERROR: 'ERROR',
  EMAIL_EXPIRED: 'EMAIL_EXPIRED',

  OTP_NOT_EXISTS: 'OTP_NOT_EXISTS',
  PHONE_NOT_EXIST: 'PHONE_NOT_EXIST',
  CLEAR_KEY_SUCCESS: 'CLEAR_KEY_SUCCESS',
  PASSWORD_NOT_MATCH: 'PASSWORD_NOT_MATCH',
};
